# Generated by Django 3.2.12 on 2023-04-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
    ]
