# Generated by Django 3.2.12 on 2023-04-27 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmodel',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
