# Generated by Django 3.2.12 on 2023-05-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlInjector',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2000)),
                ('page_src', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='sqlresult',
            old_name='tak_created_time',
            new_name='task_created_time',
        ),
        migrations.RenameField(
            model_name='sqlresult',
            old_name='location',
            new_name='title',
        ),
    ]
