# Generated by Django 3.2.12 on 2023-05-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XssResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('injection', models.CharField(max_length=255)),
                ('task_created_time', models.DateTimeField(blank=True, null=True)),
                ('task_begin_time', models.DateTimeField(blank=True, null=True)),
                ('task_end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
