# Generated by Django 3.2.12 on 2023-05-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XSS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xssresult',
            name='grade',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
