# Generated by Django 3.2.12 on 2023-04-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2000)),
                ('is_sql_scan', models.BooleanField(default=True)),
                ('is_xss_scan', models.BooleanField(default=True)),
                ('depth', models.IntegerField(default=0)),
                ('max_depth', models.IntegerField(default=5)),
                ('status_sql_scan', models.CharField(default='INIT', max_length=10)),
                ('status_xss_scan', models.CharField(default='INIT', max_length=10)),
                ('super_url', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
