# Generated by Django 3.2.12 on 2023-04-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='is_sql_scan',
            field=models.CharField(default='Y', max_length=4),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='is_xss_scan',
            field=models.CharField(default='Y', max_length=4),
        ),
    ]
