# Generated by Django 3.2.12 on 2023-04-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spider', '0002_auto_20230424_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveModel',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2000)),
                ('is_save', models.CharField(default='N', max_length=16)),
            ],
        ),
    ]
