# Generated by Django 3.2.12 on 2023-04-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spider', '0004_taskmodel_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='recv_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
